version: 2
jobs:
  build:
  
    working_directory: ~/StutterSupport
    docker:
          - image: circleci/android:api-25-alpha
    
    environment:
    
      JVM_OPTS: -Xmx3200m
   
    steps:
      - checkout
      
      - restore_cache:
      key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
 -          - v1-dependencies-{{ checksum "build.gradle" }}		 +      - run:
 -          # fallback to using the latest cache if no exact match is found		 +         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this. 
 -          - v1-dependencies-		 +         command: sudo chmod +x ./gradlew
 -		 +      - run:
 -      - run: gradle dependencies		 +          name: Download Dependencies
 -		 +          command: ./gradlew androidDependencies
         
      - save_cache:
          paths:
            - ~/.gradle
           key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
 -        		 +      - run:
 -      # run tests!		 +          name: Run Tests
 -      - run: gradlew test		 +          command: ./gradlew lint test
 -		 +      - store_artifacts:
 -		 +          path: app/build/reports
 -		 +          destination: reports
 +      - store_test_results:
 +          path: app/build/test-results
         
